---
services:
  devopsdb:
    container_name: devopsdb
    build: ./Docker-db
    ports:
      - "3306:3306"

  myapp:
    container_name: myapp_cont
    build: ./Docker-app
    ports:
      - "8082:8080"
    environment:
      DB_HOST: devopsdb
    depends_on:
      - devopsdb
